### ISSUE TITLE
Tutorials: Link to MEI Introduction from Website

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding.github.io#100]
The Introduction to MEI by A. Kijas and @raffazizzi that is part of the DFL teach toolkit ([https://dlfteach.pubpub.org/pub/intro-mei](https://dlfteach.pubpub.org/pub/intro-mei)) should be linked from the MEI website.

Any proposals where the link should be placed?

(This issue was raised at the MEI Workshop at Nashville 2019).

**Comment by margrethesb** [comment]
It should be placed under a header "Other resources" at Tutorials page.

**Comment by musicEnfanthen** [comment]
Addressed and closed by #104
