### ISSUE TITLE
BibBase style on tutorials page

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding.github.io#108]
@musicEnfanthen I would suggest to use a more compact style for external tutorials. Could you and would you add `theme=simple` to the BibBase script?

**Comment by rettinghaus** [comment]
Sorry for choosing the wrong repo.

**Comment by musicEnfanthen** [comment]
No problem, thanks for the transfer.

Will use t`heme=side` which is even more compact than `simple`

**Comment by musicEnfanthen** [comment]
Closed by #109
