### ISSUE TITLE
Errors in bibliography

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding.github.io#11]
Hello everyone,

going through the literature on [Resources/Bibliography](http://music-encoding.org/resources/bibliography.html), just stumbled over some typos and errors.

Also, despite being quite diverse, it appears quite random, not comprehensive and not up-to-date. Is this by purpose? (Is it allowed to add some titles from time to time? For example, @pe-ro 's ISMIR 2000 paper, mentioned in [About/What is the history of MEI](http://music-encoding.org/about/), is missing as well as @kepper 's PhD.) 

@pe-ro The links to your 2009 presentation "The Music Encoding Initiative (MEI) DTD and the Online Chopin Variorum Edition" are broken (both to the ppt and pdf), but I found a copy here: https://pdfs.semanticscholar.org/f216/823c759b89ad8f623cdbd0e3c6e77bc4fe7e.pdf. Do you know of any other stable URL, or should I change the link to the semanticscholar copy?

Another point one could think about is to have the `Bibliography` rendered dynamically (e.g. via [bibbase.org](https://bibbase.org/)). But this is another issue.

**Comment by musicEnfanthen** [comment]
Ok, I see, thanks for the clarification. Maybe it's worth mentioning in the title that it is intended to be only selective?

Of course your ISMIR paper is included, sorry, my fault. The link is broken, however, but it's still available here: http://ismir2000.ismir.net/papers/roland_paper.pdf (can change that link too).

By the way: How is this line to be read?

```
Roland, Perry. “The Music Encoding Initiative (MEI).” 2006. —. The Music Encoding Initiative (MEI) DTD and the OCVE. Powerpoint. University of Virginia. Charlottesville, VA, 2009. <pilot.ocve.org.uk/redist/ppt/MEIChopin.ppt>.
```

Does it mean that the 2006 and 2009 presentations are identical, or is there just a missing line break, and the 2006 one has no further bibliographic information? (Sorry for the dumb question, but I guess, the 2009 ppt rather belongs to its corresponding PDF in the following entry?)

**Comment by pe-ro** [comment]
These entries should read --
```
Roland, Perry. "The Music Encoding Initiative (MEI) DTD and the OCVE". Powerpoint. 
University of Virginia. Charlottesville, VA, 2009. 
<http://pilot.ocve.org.uk/redist/ppt/MEIChopin.ppt>.

Roland, Perry. “The Music Encoding Initiative (MEI) DTD and the Online Chopin 
Variorum Edition.” Technical report. 2009. <http://pilot.ocve.org.uk/redist/pdf/roland.pdf>.
```
They are not exactly the same.  The PowerPoint file is a presentation given at an OCVE meeting, while the PDF is a technical report delivered to the OCVE.

Thanks for cleaning up the bibliography.  Feel free to change the title on the page.

**Comment by musicEnfanthen** [comment]
Thank you again. Tried to clean things up so far and already added @kepper 's PhD diss.

If there are no objections, I'd like to add the following french publications as well  (at the moment there is only one):

- "Encodage de documents musicaux avec la MEI" by @lpugin in _Musiques orales, notations musicales et encodages numériques_, ed. by Sylvaine Leblond Martin, Paris 2016
- "Musiques orales, leur notation musicale et l'encodage numérique MEI – Music Encoding Initiative – de cette notation" by Sylvaine Leblond Martin from the same collection
- _La MEI dans tous ses états_ , Master's Thesis, University Lille 3, France, September 30, 2016 by @marie-ototoi (PDF: http://www.pas-sages.org/_preview/master/memoireMEI-2016-09-15-5.pdf)

@pe-ro For your 2006 presentation `“The Music Encoding Initiative (MEI).” 2006.` I only found this old link  `<http://www.lib.virginia.edu/digital/resndev/mei>` that is broken unfortunately. Do you know if it is still somewhere on the servers in Virginia?

**Comment by pe-ro** [comment]
Oh, it disappeared long ago.  The entry in the bibliography was a historical marker of its existence.  It can be removed.

**Comment by musicEnfanthen** [comment]
Ok, thanks, I have finished it up in #13 .
