### ISSUE TITLE
Old conference page

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding.github.io#117]
The conference page from last year seems to be broken:
https://music-encoding.org/conference/2019/
Logos are way too big and entries in the right menu are linking to the 2020 conference.

Design was affected with commit 6ec071a88f474fb4141a40b852aa7cb50f72c934 by @annakijas1 
Please revert this.

**Comment by bwbohl** [comment]
Yeah, already realised that... Last year's page is still there though. Good the at you crew assured an issue for it:wink:

**Comment by musicEnfanthen** [comment]
I guess, this is correct and by purpose? As far as I can see, there is nothing like an "old conference page" on the website, i.e. there is no link that would navigate to the landing page of a former conference. Only the PDF programs are linked from https://music-encoding.org/conference/past.html, so obiously no need to keep the old website or stylings.

The sidemenu has to link to teh 2020 conference as it is set in the config.yml globally. When you change it to link to 2019, it will also link to the 2019 sections when you are on the 2020 pages.

Of course you can change manually the url https://music-encoding.org/conference/2020/ to ask for 2019 (2018 as well). I guess this is a relict and the directories for 2018 and 2019 in https://github.com/music-encoding/music-encoding.github.io/tree/master/conference could/should be removed? But that is a question for the board to decide, I guess.

**Comment by rettinghaus** [comment]
@musicEnfanthen I've been directed there from Google. So probably best would be indeed to remove the outdated landing pages and only keep the PDFs.

**Comment by musicEnfanthen** [comment]
Maybe we would also need some redirects (always to the latest conference?) to avoid 404's for visitors coming from Google results like in your case.

**Comment by bwbohl** [comment]
personally I would like to keep at least the old conferences' detailed programs

**Comment by musicEnfanthen** [comment]
Yes, absolutely. This should be the minimum. 

I am not saying I am against keeping the landing pages of past conferences. There can be good reasons for that. I am just saying that the current website is not structured in a way that would allow us to do so. Reverting the commit 6ec071a by @annakijas1 would not have the desired effect, but break the 2020 conference's landing page.

**Comment by musicEnfanthen** [comment]
BTW, did you get already a PDF for 2019?

**Comment by bwbohl** [comment]
yes, but unfortunately it doesn't include the poster session details
