### ISSUE TITLE
Layout: content and header margins should correspond

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding.github.io#129]

**Comment by musicEnfanthen** [comment]
@bwbohl Could you provide a description of the issue please?

**Comment by bwbohl** [comment]
when I created the issue the margins of header and body did not correspond for a calmer layout theses values should be the same.

**Comment by musicEnfanthen** [comment]
@bwbohl Is this still an issue?

**Comment by musicEnfanthen** [comment]
ping @bwbohl : Can this issue be closed? Can't reproduce on FF or Chrome these days.

**Comment by bwbohl** [comment]
yes, still an issue on small layouts

![Screenshot 2022-02-01 at 23 25 31](https://user-images.githubusercontent.com/2430401/152061945-c839672f-6298-49f7-b1a8-7c17bc63267f.png)
:

**Comment by musicEnfanthen** [comment]
@bwbohl provided a fix in #304
