### ISSUE TITLE
Restructure Archive Page

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding.github.io#131]
The Archive page lists different kinds of materials, that are somewhat doubled on other pages:
* past conferences

Or might be better suited in other places:

* workshop materials
* presentations, slides, posters

Or are inconsitently linked:

* previous MEI versions

**Comment by musicEnfanthen** [comment]
Do you mind if we would remove the "Past Music Encoding Conferences" section from the Archive page in a first step. The information provided there is now included under conferences. Or is it better to give a link to the conference section? What dou you think @bwbohl @martha-thomae ?

**Comment by martha-thomae** [comment]
Hi @musicEnfanthen. Thank you for looking into this. I think it is ok to just remove it from the Archive page.

**Comment by musicEnfanthen** [comment]
Thanks.

I was wondering if the "[Previous Versions of MEI](https://music-encoding.org/archive/)" section wouldn't fit better at the end of the [schemas](https://music-encoding.org/resources/schemas.html) page?

**Comment by bwbohl** [comment]
> I was wondering if the "[Previous Versions of MEI](https://music-encoding.org/archive/)" section wouldn't fit better at the end of the [schemas](https://music-encoding.org/resources/schemas.html) page?

I think that's a good, at least that's a place where I would expect links to schemata ;-)
Maybe the Archive Section should reference the schemata section or just link to the github repo?

**Comment by musicEnfanthen** [comment]
@bwbohl Provided a fix for the discussed issue of previous versions in #302. 

Could you please indicate if the archive page would still need more restructuring at the moment, or if the issue would be resolved for now?

**Comment by bwbohl** [comment]
I think we can close it for now but someday come up with a real remake
