### ISSUE TITLE
fix xhtml:body padding on pages with bib-base (bootstrap) involvement

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding.github.io#140]
On medium and small screen sizes pages with bib-base inclusion get `padding-left:20px; padding-right:20px`. This seems due to bootstrap involvement in the bib-base inclusion.

**Comment by musicEnfanthen** [comment]
Yes, this seems to be a known issue with bib-base inclusion, see https://bibbase.userecho.com/communities/1/topics/160-bootstrap-css-conflicts-with-page

A workaround could be to have an inline `style="padding-left:inherit; padding-right:inherit"` on the `body`, but I am not sure if there are any side-effects.
