### ISSUE TITLE
guidelines sidebar search input

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding.github.io#142]
The true_search_input is too wide on large screens; the search button is being rendered outside the window

**Comment by rettinghaus** [comment]
`width: 100vw` doesn't work with the `max-width: 1296px` from `.container.grid-xl` 
see #125

**Comment by bwbohl** [comment]
the basic problem seems to be 

```CSS
.specsLayout {
  width: 100vw;
}
```

**Comment by bwbohl** [comment]
conflicts with general page layout of the MEI website which moves the nav-column outside of the viewport

**Comment by bwbohl** [comment]
do we really need to have the page wieder for the specs? then maybe we should use another defined _layout? Or we could move the specs navbar to a responsive menu like the new main menu

**Comment by bwbohl** [comment]
closed with #145
