### ISSUE TITLE
make MEC2020 code of conduct top-level menu content

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding.github.io#151]
The code of conduct written for MEC2020 seems to be an appropriate general statement. What about keeping this as general statement and move it to the conference section and main menu?

**Comment by musicEnfanthen** [comment]
The MEC2020 code of conduct is here: https://github.com/music-encoding/music-encoding.github.io/blob/master/_conferences/2020/code-of-conduct.html

**Comment by musicEnfanthen** [comment]
Closed by #221
