### ISSUE TITLE
Dead link on MEI tutorial page

### ISSUE THREAD

**Issue by musicnerd** [music-encoding/music-encoding.github.io#158]
I noticed there is a dead link (404 error) on the MEI tutorial page where there is supposed to be a link to "tutorial on XML basics"

**Comment by bwbohl** [comment]
Hi @musicnerd, thanks for reporting!

**Comment by musicEnfanthen** [comment]
Yes, thanks for spotting this @musicnerd . And thanks for the quick fix @bwbohl . Please see also https://github.com/music-encoding/music-encoding.github.io/pull/159#discussion_r480024434
