### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by doerners** [music-encoding/music-encoding.github.io#189]
There are some broken links that have been identified during the developer workshop where I couldn't find any working equivalent or just don't know what the course of action might be.

Any comments or possible solutions/decisions are much appreciated and maybe someone from the community also knows of working alternatives.

The precise links (with additional comments) are as follows:

FILE: ./_projects/ema.md
https://github.com/umd-mith/ema/tree/master/Omas → Status: 404
**Might it be sufficient to just link to the ema repo?**

FILE: ./_projects/meico.md
http://www.zemfi.de/resources/meico-mei-converter/ → Status: 404
**Couldn't find any working alternative. Should this link just be deleted?**

 FILE: ./_posts/2015-07-21-mec-2016-call.md
http://music-encoding.org/community/conference/call-for-proposals/ → Status: 404
http://music-encoding.org/community/conference/ → Status: 404
FILE: ./_posts/2016-11-21-elections.md
http://music-encoding.org/community/mei-organization/mei-by-laws/ → Status: 404
FILE: ./_posts/2015-06-17-mec-2016-dates.md
http://music-encoding.org/community/conference/ → Status: 404
FILE: ./_posts/2017-03-14-mec-2017-program.md
http://music-encoding.org/community/conference/tours17/program/ → Status: 404
 FILE: ./_posts/2016-10-14-mec-2017-call.md
 http://music-encoding.org/community/conference/call-for-proposals/ → Status: 404
**All those can be found on the News and Events page. I was wondering if we even still need those links/posts since the posts are not quite current anymore. So should we make an effort to replace them or can they just be deleted or archived, respectively?**

FILE: ./community/mei-board/protocols/2017-05-17_Face-to-Face-Meeting-MEC2017-Tours.md
http://music-encoding.org/proceedings → Status: 404
**Is there a site where the proceedings workflow is documented? – I couldn't find any.
Otherwise is this even needed anymore?**

 FILE: ./community/mei-board/elections/2018/candidates.md
https://sites.google.com/fcsh.unl.pt/elsadeluca/online-publications?authuser=0 → Status: 404
**Do we still need this link? Otherwise maybe we should link to: https://sites.google.com/fcsh.unl.pt/elsadeluca/publications#h.p_sC0zG9ee-Sy9**

FILE: ./conference/hosting-guidelines.md
http://music-encoding.org/community/ → Status: 404
http://music-encoding.org/community/conference → Status: 404
**What could be an alternative? For the first link maybe just a link to the "About" page?**

./unused/downloads.md
http://www.music-encoding.org/schema/current/mei-CMN.rng → Status: 404
http://www.music-encoding.org/schema/current/mei-Mensural.rng → Status: 404
http://www.music-encoding.org/schema/current/mei-Neumes.rng → Status: 404
http://www.music-encoding.org/schema/current/mei-all.rng → Status: 404
http://www.music-encoding.org/schema/current/mei-all_anyStart.rng → Status: 404
http://music-encoding.org/wp-content/uploads/2015/04/sampleEncoding.jpg → Status: 404
http://music-encoding.org/wp-content/uploads/2015/04/sampleEncoding-300x176.jpg → Status: 404
./unused/community.md
http://music-encoding.org/community/mei-organization/mei-board/ → Status: 404
http://music-encoding.org/community/mei-organization/technical-team/ → Status: 404
http://music-encoding.org/community/mei-organization/mei-by-laws/ → Status: 404
./unused/organization.md
https://music-encoding.org/wordpress/?page_id=16 → Status: 404
https://music-encoding.org/wordpress/?page_id=18 → Status: 404
**Should we even bother with those "unused" links?** 

https://music-encoding.org/conference/2021/code-of-conduct/
**Is this just a matter of content to come?**

**Comment by rettinghaus** [comment]
The code for Omas now is actually here: https://github.com/music-addressability/ema-for-mei
For meico there seems to be no official site any more, so the complete last sentence should be removed.

**Comment by th-we** [comment]
Concerning meico: What about this? https://github.com/cemfi/meico/

**Comment by rettinghaus** [comment]
@th-we There is link to the GitHub repo already, it was just about the missing project website.

**Comment by musicEnfanthen** [comment]
For the 2016 conference posts, we could work with Wayback Machine that has snapshots of the CfP and Website:

2016:
https://web.archive.org/web/20150710210430/http://music-encoding.org/community/conference/
https://web.archive.org/web/20160505023112/http://music-encoding.org/community/conference/call-for-proposals/

**Comment by musicEnfanthen** [comment]
The 2021 Code of Conduct is a placeholder to be filled soon.

**Comment by musicEnfanthen** [comment]
CfP 2017: https://web.archive.org/web/20161020120633/http://music-encoding.org/community/conference/call-for-proposals/

**Comment by musicEnfanthen** [comment]
Proceedings workflow is in a separate repo: https://github.com/music-encoding/mec-proceedings

**Comment by musicEnfanthen** [comment]
Hosting guidelines: 
Yes, a link to the `About` page for the first link comes closest to the previous content. 
The second link should read https://music-encoding.org/conference

**Comment by rettinghaus** [comment]
We should decide if we want to rely on Wayback Machine. If so, it would be cool if GitHub Actions could check there and directly replace broken links.

**Comment by musicEnfanthen** [comment]
As far as I can see, the need to rely on Wayback Machine would only affect 5–10 links (since the original links are not available any more). As soon as these links are fixed, there would be no need for the GH actions to replace any fixed links, wouldn't it? (In general, it would be hard to detect automatically if any snapshot corresponds to the target state of a certain link.)

**Comment by musicEnfanthen** [comment]
The image in the unused sample encodings page was a screenshot and encoding of "An die ferne Geliebte" op. 98: 
https://web.archive.org/web/20170217074250/http://music-encoding.org/wp-content/uploads/2015/04/sampleEncoding.jpg
(in page context: https://web.archive.org/web/20161020115515/http://music-encoding.org/downloads/encodings/)

**Comment by musicEnfanthen** [comment]
After talking to @axelberndt , the broken zemfi link could just link to the main webpage: http://www.zemfi.de/ 
He also proposed to move the whole meico section to `Tools/Community Tools` (what is not related to the current issue and should be done in another step)

**Comment by axelberndt** [comment]
Better use this link: [https://github.com/cemfi/meico]( https://github.com/cemfi/meico). It brings you directly to the tool.

**Comment by doerners** [comment]
I would propose to link to the webpage (http://www.zemfi.de/) since there is already a link to the code on GitHub in one of the previous sentences.

**Comment by axelberndt** [comment]
OK, agree.

**Comment by bwbohl** [comment]
with #219 closed this might be closed, too?

**Comment by musicEnfanthen** [comment]
Yes, please. 

Thank you @doerners , @rettinghaus , @th-we and @axelberndt for your support and contributions, esp. @doerners for manually identifying all the broken links!

**Comment by musicEnfanthen** [comment]
Closed by #190 and #219
