### ISSUE TITLE
Links to PDFs and DOIs don't work on Firefox or Chrome

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding.github.io#20]
@pe-ro metions in #17 that the links to PDF and DOIs do not work for him on Firefox or Chrome when clicking directly on it (nothing happens). Right-clicking and open it in a new tab, works fine.

**Comment by rettinghaus** [comment]
I did a test on Linux (Ubuntu 18.04), Windows 7, and macOS (High Sierra) and encountered no problems at all. 
macOS: Safari, Firefox, Chrome, Opera work fine
Windows: Firefox, Opera work fine
Linux: Firefox, Chromium, Chrome, Opera, Epiphany work fine

**Comment by pe-ro** [comment]
I'm using Windows 7 Enterprise.  I don't think I have any "strange settings" in either the operating system or the browsers, though I do use AdBlock Plus and Ghostery, both of which are up-to-date.  Disabling these extensions, however, has no effect on the problem.

**Comment by musicEnfanthen** [comment]
Ok, I see. On Mac and Firefox I still can't open any links from the bibliography that are pointing to an external source, too. On Chrome (Mac) it's working fine. 

Just started FF in [Safe Mode](https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode) that "temporarily turns off hardware acceleration, resets some settings, and disables add-ons (extensions and themes) that might be causing problems" and links were clickable again.

Will have to narrow it down further.

**Comment by musicEnfanthen** [comment]
There seems to bea solution: At least, turning off "tracking protection" in FireFox resulted in the expected behaviour, links were clickable again.

Could you eventually check please, if this is working for you, too, @pe-ro ? (Maybe on Chrome there is something similar?)

And @rettinghaus , could you please check if turning "tracking protection" on is resulting in the non-clickable state?

**Comment by rettinghaus** [comment]
Re-checked and confirmed on Linux and Windows with Firefox. This happens while "Private Browsing" apparently due to the advanced tracking protection. 

There was a similar issue reported to bibbase.org:
https://bibbase.userecho.com/communities/1/topics/242-safari-prevent-cross-site-tracking-option

**Comment by rettinghaus** [comment]
Looks like BibBase uses doubleclick, requests go to stats.g.doubleclick.net. (Needs to be verified)

**Comment by musicEnfanthen** [comment]
Ok, thanks for the confirmation. Will report it to BibBase and see what they can do.

**Comment by rettinghaus** [comment]
This is a BibBaseBug, addressed here:
https://bibbase.userecho.com/communities/1/topics/256-external-links-broken
Closing this one for now.

**Comment by pe-ro** [comment]
Indeed, turning off tracking protection in Firefox makes the links clickable again.  But it raises privacy concerns, of course.

**Comment by chfritz** [comment]
@pe-ro you are absolutely right about the privacy concerns! We've now fixed this in BibBase (https://bibbase.userecho.com/communities/1/topics/256-external-links-broken#comment-681).

**Comment by musicEnfanthen** [comment]
Thanks a lot @chfritz . Works for me now with tracking protection turned on.

Can you confirm that it works for you too, @pe-ro ? Then we can close this closed issue.
