### ISSUE TITLE
Technical Team needs Update

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding.github.io#210]
The page community/tenical team need to be updated as it holds old information

**Comment by bwbohl** [comment]
Discussion at the 2021-04-29 ODD Thursday brought up several things are coming together or should be considered together:

1. list should be revised more often
2. as easy as it is to put names on such a list it might prove unfavourable to remove them (due to different reasons, e.g. someone heavily contributed to MEI in the past but is just not available at the moment)
3. should it even be called Technical Team anymore, as contributions might be beyond technicalities, anyway, e.g. guidelines or other forms of dissemination of MEI
4. how to relate this to repo access rights on github?
6. it would be nice if one could add labels to ticket or PRs and assign reviewers (only a few individuals get listed at the moment)

Questions like theses should be considered in a proposal how to reorganise and especially make clear to the uninitiated  (documentation) how easy it is to contribute to MEI.

**Comment by ahankinson** [comment]
What is still not clear is what the process is to get a contribution reviewed and merged, but the composition and responsibilities of the Technical Team was distilled here after extensive discussions: https://github.com/music-encoding/music-encoding/blob/develop/CONTRIBUTING.md

If the Technical Team documentation and processes are updated, it might be helpful to look at this documentation first to see if there are still any nuggets of wisdom there.

**Comment by ahankinson** [comment]
If I recall correctly the "Technical Team" was named as such as the members were supposed to be given elevated GH privileges.

**Comment by bwbohl** [comment]
in response to the two comments above by @ahankinson:

Wouldn't it be consequent then, to add any member counting themselves as part of the Technical Team to the "Core Contributors" Team? And actually renaming it to "Technical Team"?

**Comment by ahankinson** [comment]
I think there are two groups, but this is just my own opinion — it should probably be decided by the co-chairs:

1. Technical team: people with technical experience but without lots of experience working on the spec. They could be given elevated commit privileges for the non-spec repos (website, guidelines) and privileges for helping to manage and triage spec issues. When they become more comfortable with the spec, they can then move into the second group…
2. core contributors. These are the people who have experience and have shown themselves to be trustworthy for making changes to the spec. I don’t know if “core contributors” is the right term, but I do think we need to apprentice people to having spec-changing rights. I would hope we would still keep the “two approving reviews” for the spec anyway, so the risk of bad commits is small, but I think we do need some tiered privilege levels.

thoughts?

**Comment by bwbohl** [comment]
completly with you
