### ISSUE TITLE
bibliography: links to articles

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding.github.io#23]
In #19 there was a discussion on how extensive the bibliography should be enriched with links. 
Basically a DOI provides a link to the document in question (see https://www.doi.org/). 
As it is convenient to provide an additional direct link to a pdf (where available), the question is, if this should be added even if the direct access is restricted in some form and on how to state this restriction appropriately within the bibliographic entry.

**Comment by musicEnfanthen** [comment]
> @musicEnfanthen is there a good way to provide the needed note to the pdf links?

As mentioned in #19 , one could add a `note` field to the bib file entry in question that says something like "PDF available online by subscription" (phrase borrowed from OUP as an example).

`note = {PDF available online by subscription.}`

**Comment by rettinghaus** [comment]
If I'm not mistaken, this would say something about the document, but not about the link.

**Comment by musicEnfanthen** [comment]
So what would you suggest?

**Comment by rettinghaus** [comment]
Personally I'd prefer to just keep the DOIs in those cases and go without a specific PDF link.

**Comment by musicEnfanthen** [comment]
So if I understand correctly, for any direct accessable item give the DOI and a direct link to the PDF or other format (if available), and for restricted items give just the DOI that links to a "landing page" which provides further infos. If there is no DOI, just give the direct link to the "landing page" of the document.

Everybody okay with that?

**Comment by kepper** [comment]
sounds good

**Comment by musicEnfanthen** [comment]
Closing it as there seems to be consens about the topic.
