### ISSUE TITLE
Layout: Guidelines sidemenu and search box responsiveness

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding.github.io#303]
When making the window smaller, the side menu should disappear, but it just moves to the lower end of the page. 
Also there is an alignment issue with the search box.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/7693447/151711853-7455dce4-95f7-4ead-8807-09df750a3e6d.png">

**Comment by musicEnfanthen** [comment]
Thanks for the catch. 

For reference: music-encoding/music-encoding/issues/745

**Comment by rettinghaus** [comment]
@musicEnfanthen @kepper Turn out it is a wrong class name in the xslt. Fixed this part over in music-encoding/music-encoding#903

**Comment by bwbohl** [comment]
@rettinghaus could you recheck, now after #903 is merged?

**Comment by rettinghaus** [comment]
Search box position still has to be fixed.
