### ISSUE TITLE
Broken links in the community/board page

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding.github.io#31]
The first three links in https://github.com/music-encoding/music-encoding.github.io/blob/db091c3a0cb6e5bdcb1c209d0d048a3d005e8b81/community/mei-board.md#protocols-of-board-meetings are broken. Not sure where they need to point.

**Comment by KristinaRichts** [comment]
Did you archive the pages of the old website anywhere? I think, there were own pages for the protocols, but I can't find them in the new repository...

**Comment by lpugin** [comment]
@kepper must have them.

**Comment by lpugin** [comment]
Was this fixed?

**Comment by KristinaRichts** [comment]
now it should be. I iforgot to add the links to the parent page :)
