### ISSUE TITLE
Validation warnings in Oxygen 

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding.github.io#48]
Older versions of Oxygen do not accept Let's Encrypt secured links for validation. We should add a note about that, and that this can be resolved by accepting all certificates.

**Comment by ahankinson** [comment]
How old?

**Comment by rettinghaus** [comment]
Version 18 and older.

**Comment by musicEnfanthen** [comment]
How is this issue connected to Tutorials or training? 

@rettinghaus Where do you like to add that note?

**Comment by bwbohl** [comment]
I' like to provide that info somewhere… Either it could go into the tutorial, or in a general Tool-Info area?

**Comment by musicEnfanthen** [comment]
Maybe this would be good to have in something like a technical setup section? Actually, there is nothing like that on the page yet, isn't it? Or is guideline's chapter [1.3. Sample Encodings and Tools for MEI ](https://music-encoding.org/guidelines/v4/content/introduction.html#samplesTools) meant to address this topic?

**Comment by kepper** [comment]
I wouldn't include that information in the Guidelines – it's seems to stretch their task too far. I'd much rather put this on the website as a note. It doesn't fit perfectly into the current Tools page, but that seems to be the right place from my perspective…

**Comment by musicEnfanthen** [comment]
@rettinghaus @bwbohl Is this still an issue? If so, would you mind to prepare a PR?

**Comment by rettinghaus** [comment]
I would guess so, but I don't have an old version anymore to test it. 
But a note about Let's encrypt should be put somewhere anyway, I think.

**Comment by musicEnfanthen** [comment]
I still don't get why this should go on the website, rather than being documented in a dedicated section on Github (but don't have strong opinion about that). 

@rettinghaus Could you prepare the wording of the note? How should it read?

**Comment by bwbohl** [comment]
Hmm… just wondering, too where this should go. Starting things like this on the website would make me expect similar setup descriptions for more environments, e.g. Windows, Mac, Linux and open source / freeware vs. commercial /proprietary software. I see two alternatives, though:

1. GitHub Wiki
2. GitHub Discussions

From my point of view Wiki:s tend to be a bag of many things and to get a mess rather sooner than later. So I'd prefer 2. What about you guys?

**Comment by bwbohl** [comment]
One thing that might be a bit of a problem with putting things on Github is that they're always tied to one repo, not the organization.

**Comment by musicEnfanthen** [comment]
Maybe this question should be discussed on a broader scale (SLACK or MEI-L) to get a better picture where most people would expect such a info to be found?

**Comment by rettinghaus** [comment]
This issue is quite old by now. I guess nobody would have the idea to try out an outdated version of oxygen anymore and _Let's encrypt_ certificates are accepted widely. 
Maybe we just close this?

**Comment by bwbohl** [comment]
I used to work with oxygen 18 until just a couple of months ago… But I guess you're right. If there's a place, maybe it should be https://github.com/music-encoding/oXygen-MEI-addon

I'm currently a bit busy but planning to get back on that.

**Comment by rettinghaus** [comment]
Closing this now. We can open (and think about) it again if somebody still has issues.
