### ISSUE TITLE
Missing nominations link

### ISSUE THREAD

**Issue by annakijas1** [music-encoding/music-encoding.github.io#534]
The nominations post is missing the link to submit a nomination - https://github.com/music-encoding/music-encoding.github.io/blob/main/_posts/2023-10-30-call-for-nominations.md

**Comment by bwbohl** [comment]
That was intentional, the same way we did the last years. The nomination link is distributed via MEI-L membership and as convenience also via the SLACK channel.

**Comment by annakijas1** [comment]
Ah, of course. I will close this issue.
