### ISSUE TITLE
Tools: reconsider whether all old "official" tools should be listed

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding.github.io#605]
This one is very confusing. It speaks about the "Schema", points to the guidelines website and links the main repo as repository...?

_Originally posted by @musicEnfanthen in https://github.com/music-encoding/music-encoding.github.io/pull/588#discussion_r1532132127_

**Comment by bwbohl** [comment]
@musicEnfanthen can this be closed after the redesign of the Tools section?

**Comment by musicEnfanthen** [comment]
I think you opened it AFTER the redesign of the Tools section ;) 

It was mostly about the confusing info in the "tool" called "MEI Schema" which is still confusing.

**Comment by bwbohl** [comment]
Jikes, you’re absolutely right. Looking at it, I think we should delete it from the tools collection.
