### ISSUE TITLE
Swap Editor and Instructions place in tutorials

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding.github.io#67]
When progressing to a new stage in the MEI Tutorials, the instructions are of variable length. Thus when completing a tutorial, the content of the page 'jumps around' and, specifically, the position of the editor. 

To prevent this, the position of the editor should be fixed at the top of the page, and the instructions should then be updated underneath it.

**Comment by musicEnfanthen** [comment]
Thanks a lot for your helpful feedback. Placing the editor at the top of the page has the disadvantage that, for longer tutorial descriptions, you would have to scroll back to the top and would not see the instructions (at the bottom) anymore. That could be even more disturbing. So after discussion we decided not to address this at the moment (what does not mean it is the end of all truth).

I am closing this for now, but please reopen at any time.
