### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by siennamw** [music-encoding/music-encoding.github.io#8]
It looks like the tutorial has been removed.  It was out of date, but it seems a shame to have nothing at all for beginners looking to get started.  I'd be happy to contribute to putting up a new and improved version if nobody else is working on it.  Any suggestions about content/structure would also be very helpful.

**Comment by musicEnfanthen** [comment]
No problem at all. There is further work going on in the "tutorials" branch. Feel free to have a look there whenever it is convenient for you.

**Comment by ahankinson** [comment]
I think this can be closed now, with the publication of the tutorials on the site.
